-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.bat_dong_san
(
    bds_id serial NOT NULL,
    ten_bds character varying(255) COLLATE pg_catalog."default" NOT NULL,
    dia_chi text COLLATE pg_catalog."default" NOT NULL,
    gia_thue numeric(15, 2) NOT NULL,
    dien_tich integer,
    mo_ta text COLLATE pg_catalog."default",
    trang_thai character varying(20) COLLATE pg_catalog."default" DEFAULT 'trong'::character varying,
    lat double precision,
    lng double precision,
    ngay_tao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    loai_id integer,
    nguoi_dung_id integer,
    CONSTRAINT bat_dong_san_pkey PRIMARY KEY (bds_id)
);

CREATE TABLE IF NOT EXISTS public.bds_tien_ich
(
    bds_id integer NOT NULL,
    tien_ich_id integer NOT NULL,
    CONSTRAINT bds_tien_ich_pkey PRIMARY KEY (bds_id, tien_ich_id)
);

CREATE TABLE IF NOT EXISTS public.danh_gia
(
    danh_gia_id serial NOT NULL,
    so_sao integer,
    noi_dung text COLLATE pg_catalog."default",
    ngay_tao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    nguoi_dung_id integer,
    bds_id integer,
    CONSTRAINT danh_gia_pkey PRIMARY KEY (danh_gia_id)
);

CREATE TABLE IF NOT EXISTS public.dat_lich
(
    dat_lich_id serial NOT NULL,
    thoi_gian_bat_dau timestamp without time zone NOT NULL,
    thoi_gian_ket_thuc timestamp without time zone NOT NULL,
    trang_thai character varying(20) COLLATE pg_catalog."default" DEFAULT 'cho_duyet'::character varying,
    ngay_tao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    nguoi_dung_id integer,
    bds_id integer,
    CONSTRAINT dat_lich_pkey PRIMARY KEY (dat_lich_id)
);

CREATE TABLE IF NOT EXISTS public.hinh_anh_bds
(
    hinh_id serial NOT NULL,
    bds_id integer,
    url text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT hinh_anh_bds_pkey PRIMARY KEY (hinh_id)
);

CREATE TABLE IF NOT EXISTS public.loai_bat_dong_san
(
    loai_id serial NOT NULL,
    ten_loai character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT loai_bat_dong_san_pkey PRIMARY KEY (loai_id)
);

CREATE TABLE IF NOT EXISTS public.nguoi_dung
(
    nguoi_dung_id serial NOT NULL,
    ho_ten character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    mat_khau character varying(255) COLLATE pg_catalog."default" NOT NULL,
    so_dien_thoai character varying(20) COLLATE pg_catalog."default",
    ngay_tao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    role_id integer,
    CONSTRAINT nguoi_dung_pkey PRIMARY KEY (nguoi_dung_id),
    CONSTRAINT nguoi_dung_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.role
(
    role_id serial NOT NULL,
    ten_role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    mo_ta text COLLATE pg_catalog."default",
    CONSTRAINT role_pkey PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS public.thong_bao
(
    thong_bao_id serial NOT NULL,
    tieu_de character varying(255) COLLATE pg_catalog."default",
    noi_dung text COLLATE pg_catalog."default",
    da_doc boolean DEFAULT false,
    ngay_tao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    nguoi_dung_id integer,
    CONSTRAINT thong_bao_pkey PRIMARY KEY (thong_bao_id)
);

CREATE TABLE IF NOT EXISTS public.tien_ich
(
    tien_ich_id serial NOT NULL,
    tentienich character varying(100) COLLATE pg_catalog."default" NOT NULL,
    motatienich text COLLATE pg_catalog."default",
    CONSTRAINT tien_ich_pkey PRIMARY KEY (tien_ich_id)
);

CREATE TABLE IF NOT EXISTS public.tin_nhan
(
    tin_nhan_id serial NOT NULL,
    gui_tu_id integer,
    gui_den_id integer,
    noi_dung text COLLATE pg_catalog."default" NOT NULL,
    thoi_gian_gui timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    trang_thai character varying(20) COLLATE pg_catalog."default" DEFAULT 'sent'::character varying,
    CONSTRAINT tin_nhan_pkey PRIMARY KEY (tin_nhan_id)
);

CREATE TABLE IF NOT EXISTS public.yeu_thich
(
    nguoi_dung_id integer NOT NULL,
    bds_id integer NOT NULL,
    CONSTRAINT yeu_thich_pkey PRIMARY KEY (nguoi_dung_id, bds_id)
);

ALTER TABLE IF EXISTS public.bat_dong_san
    ADD CONSTRAINT bat_dong_san_loai_id_fkey FOREIGN KEY (loai_id)
    REFERENCES public.loai_bat_dong_san (loai_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bat_dong_san
    ADD CONSTRAINT bat_dong_san_nguoi_dung_id_fkey FOREIGN KEY (nguoi_dung_id)
    REFERENCES public.nguoi_dung (nguoi_dung_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bds_tien_ich
    ADD CONSTRAINT bds_tien_ich_bds_id_fkey FOREIGN KEY (bds_id)
    REFERENCES public.bat_dong_san (bds_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.bds_tien_ich
    ADD CONSTRAINT bds_tien_ich_tien_ich_id_fkey FOREIGN KEY (tien_ich_id)
    REFERENCES public.tien_ich (tien_ich_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.danh_gia
    ADD CONSTRAINT danh_gia_bds_id_fkey FOREIGN KEY (bds_id)
    REFERENCES public.bat_dong_san (bds_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.danh_gia
    ADD CONSTRAINT danh_gia_nguoi_dung_id_fkey FOREIGN KEY (nguoi_dung_id)
    REFERENCES public.nguoi_dung (nguoi_dung_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.dat_lich
    ADD CONSTRAINT dat_lich_bds_id_fkey FOREIGN KEY (bds_id)
    REFERENCES public.bat_dong_san (bds_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.dat_lich
    ADD CONSTRAINT dat_lich_nguoi_dung_id_fkey FOREIGN KEY (nguoi_dung_id)
    REFERENCES public.nguoi_dung (nguoi_dung_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.hinh_anh_bds
    ADD CONSTRAINT hinh_anh_bds_bds_id_fkey FOREIGN KEY (bds_id)
    REFERENCES public.bat_dong_san (bds_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.nguoi_dung
    ADD CONSTRAINT nguoi_dung_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES public.role (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.thong_bao
    ADD CONSTRAINT thong_bao_nguoi_dung_id_fkey FOREIGN KEY (nguoi_dung_id)
    REFERENCES public.nguoi_dung (nguoi_dung_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tin_nhan
    ADD CONSTRAINT tin_nhan_gui_den_id_fkey FOREIGN KEY (gui_den_id)
    REFERENCES public.nguoi_dung (nguoi_dung_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tin_nhan
    ADD CONSTRAINT tin_nhan_gui_tu_id_fkey FOREIGN KEY (gui_tu_id)
    REFERENCES public.nguoi_dung (nguoi_dung_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.yeu_thich
    ADD CONSTRAINT yeu_thich_bds_id_fkey FOREIGN KEY (bds_id)
    REFERENCES public.bat_dong_san (bds_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.yeu_thich
    ADD CONSTRAINT yeu_thich_nguoi_dung_id_fkey FOREIGN KEY (nguoi_dung_id)
    REFERENCES public.nguoi_dung (nguoi_dung_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

-- Insert Default Roles
INSERT INTO public.role (role_id, ten_role, mo_ta) VALUES 
      (1, 'Admin', 'Quan tri vien'),
      (2, 'User', 'Nguoi dung (Thue & Cho thue)')
      ON CONFLICT (role_id) DO NOTHING;

END;
